name: Sync
api: '1.12.2'
version: '${version}'
main: cf.wangyu1745.sync.Sync
depend:
  - Vault
authors: [ wangyu ]
description: money sync,backpack sync(support mod items)
commands:
  gather:
    aliases: [ga]
    usage: gather
    description: Transferring money from different servers to the current server